### ISSUE TITLE
Deletion of Instances

### ISSUE THREAD

**Issue by ryanboerner** [BlackCoyote/dScripts#1]
For some reason my instances are just hanging around and not being deleted when the person leaves the instance. I am using the same script used by the example pirate dungeon script in spigot 1.10 with the latest instancing script and denizen #600

**Comment by BlackCoyote** [comment]
hey, can you try updating to the latest version, see if that fixes it?

**Comment by BlackCoyote** [comment]
(also sorry for the late response, github never notified me about this issue)

**Comment by BlackCoyote** [comment]
:(

**Comment by BlackCoyote** [comment]
heavily tested, issue cannot be replicated!
