### ISSUE TITLE
French traduction

### ISSUE THREAD

**Issue by Astrareach** [BlackCoyote/dScripts#2]
I will post french traduction for the Dtown script here !

**Comment by BlackCoyote** [comment]
I will let you know in this issue when the translation system is available, and show you the template :)

**Comment by BlackCoyote** [comment]
https://github.com/BlackCoyote/dScripts/commit/cdf65b8daad86c85e6812925c100465110ca48bf#diff-91b2054ee7a2b2d51ef63884a5d3476bR1109

The script should be able to have configurable languages now, if you'd like to contribute to it, the link will show the line at which the language configuration stands - if you could copy that and translate all those actual sentences in there, i will include it to the official version!

**Comment by Astrareach** [comment]
Traduction done for french! :)
